namespace Weatherservice
{
    public enum SignificantWeather
    {
        Sun = 1,
        LightCloud = 2,
        PartlyCloud = 3,
        Cloud = 4,
        LightRainSun = 5,
        LightRainThunderSun = 6,
        SleetSun = 7,
        SnowSun = 8,
        LightRain = 9,
        Rain = 10,
        RainThunder = 11,
        Sleet = 12,
        Snow = 13,
        SnowThunder = 14,
        Fog = 15,
        SleetSunThunder = 20,
        SnowSunThunder = 21,
        LightRainThunder = 22,
        SleetThunder = 23,
        DrizzleThunderSun = 24,
        RainThunderSun = 25,
        LightSleetThunderSun = 26,
        HeavySleetThunderSun = 27,
        LightSnowThunderSun = 28,
        HeavySnowThunderSun = 29,
        DrizzleThunder = 30,
        LightSleetThunder = 31,
        HeavySleetThunder = 32,
        LightSnowThunder = 33,
        HeavySnowThunder = 34,
        DrizzleSun = 40,
        RainSun = 41,
        LightSleetSun = 42,
        HeavySleetSun = 43,
        LightSnowSun = 44,
        HeavysnowSun = 45,
        Drizzle = 46,
        LightSleet = 47,
        HeavySleet = 48,
        LightSnow = 49,
        HeavySnow = 50,
        Dark_Sun = 101,
        Dark_LightCloud = 102,
        Dark_PartlyCloud = 103,
        Dark_HeavySnowThunderSun = 129
    }
}
