@startuml
class RatingService {
    + RatingService(db:RatingContext)
    + InsertTeacherRating(teacherId:int, ratingDtos:IEnumerable<RatingDto>) : void
    + InsertSchoolRating(schoolId:int, ratingDtos:IEnumerable<RatingDto>) : void
    + GetSchoolStatistics(schoolId:int) : SchoolStat
}
class RatingDto {
    + CategoryId : int <<get>> <<set>>
    + Value : int <<get>> <<set>>
}
class SchoolStat {
    + SchoolNumber : int <<get>> <<set>>
}
class Category {
    + Name : string <<get>> <<set>>
    + AvgValue : decimal <<get>> <<set>>
}
class "List`1"<T> {
}
RatingService +-- RatingDto
RatingService +-- SchoolStat
SchoolStat --> "Categories<Category>" "List`1"
SchoolStat +-- Category
@enduml
