@startuml
class Startup {
    + Startup(configuration:IConfiguration)
    + ConfigureServices(services:IServiceCollection) : void
    + Configure(app:IApplicationBuilder) : void
}
Startup --> "Configuration" IConfiguration
@enduml
