@startuml
class TeacherRating {
    + TeacherId : int <<get>> <<set>>
    + RatingCategoryId : int <<get>> <<set>>
}
Rating <|-- TeacherRating
TeacherRating --> "Teacher" Teacher
TeacherRating --> "RatingCategory" TeacherRatingCategory
@enduml
