@startuml
class Teacher {
    + Id : int <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + SchoolId : int <<get>> <<set>>
}
class "List`1"<T> {
}
Teacher --> "Name" Name
Teacher --> "School" School
Teacher --> "TeacherRatings<TeacherRating>" "List`1"
@enduml
