@startuml
class RatingContext {
    + RatingContext(options:DbContextOptions)
    + GetSchoolBySchoolNr(schoolNumber:int) : School
    + GetTeachersBySchool(schoolId:int) : IQueryable<Teacher>
    + GetAverageTeacherRating(teacherId:int, categoryId:int) : decimal
    + GetAverageTeacherRating(teacherId:int, categoryId:int, ratedFrom:DateTime) : decimal
    + Seed() : void
}
class "DbSet`1"<T> {
}
DbContext <|-- RatingContext
RatingContext --> "Schools<School>" "DbSet`1"
RatingContext --> "Ratings<Rating>" "DbSet`1"
RatingContext --> "RatingCategories<RatingCategory>" "DbSet`1"
RatingContext --> "SchoolRatings<SchoolRating>" "DbSet`1"
RatingContext --> "SchoolRatingCategories<SchoolRatingCategory>" "DbSet`1"
RatingContext --> "Teachers<Teacher>" "DbSet`1"
RatingContext --> "TeacherRatings<TeacherRating>" "DbSet`1"
RatingContext --> "TeacherRatingCategories<TeacherRatingCategory>" "DbSet`1"
@enduml
