@startuml
class TestController {
    + TestController(service:RatingService, db:RatingContext)
    + GetSchoolStatistics(schoolId:int) : IActionResult
    + GetSchoolBySchoolNr(schoolNumber:int) : IActionResult
    + GetTeachersBySchool(schoolId:int) : IActionResult
    + GetAverageTeacherRating(teacherId:int, categoryId:int) : IActionResult
    + GetAverageTeacherRating(teacherId:int, categoryId:int, ratedFrom:DateTime) : IActionResult
}
ControllerBase <|-- TestController
@enduml
